---
# Default values.
# Declare variables to be passed into your templates.
#
# Variables in `helm_deploy/values-[env].yaml` will take precedence.

generic-service:
  nameOverride: hmpps-mailbox-register
  productId: DPS030 # TODO: Update with correct product ID

  # the IRSA service account name for accessing AWS resources
  # serviceAccountName: "hmpps-mailbox-register"

  replicaCount: 2

  image:
    repository: ghcr.io/ministryofjustice/hmpps-mailbox-register
    tag: app_version # override at deployment time
    port: 3000

  ingress:
    enabled: true
    tlsSecretName: hmpps-mailbox-register-cert

  # https://github.com/ministryofjustice/hmpps-ip-allowlists/blob/main/ip-allowlist-groups.yaml
  allowlist:
    groups:
      - digital_staff_and_mojo
      - moj_cloud_platform

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 50%

  livenessProbe:
    httpGet:
      path: /ping

  readinessProbe:
    httpGet:
      path: /ping

  # Environment variables to load into the deployment
  env:
    NODE_ENV: 'production'
    REDIS_ENABLED: 'true'
    REDIS_TLS_ENABLED: 'true'
    TOKEN_VERIFICATION_ENABLED: 'true'
    AUDIT_SQS_REGION: 'eu-west-2'
    AUDIT_SERVICE_NAME: 'UNASSIGNED'

  # Pre-existing kubernetes secrets to load as environment variables in the deployment.
  # namespace_secrets:
  #   [name of kubernetes secret]:
  #     [name of environment variable as seen by app]: [key of kubernetes secret to load]
  namespace_secrets:
    hmpps-auth:
      AUTH_CODE_CLIENT_ID: 'AUTH_CODE_CLIENT_ID'
      AUTH_CODE_CLIENT_SECRET: 'AUTH_CODE_CLIENT_SECRET'
      CLIENT_CREDS_CLIENT_ID: 'CLIENT_CREDS_CLIENT_ID'
      CLIENT_CREDS_CLIENT_SECRET: 'CLIENT_CREDS_CLIENT_SECRET'
    hmpps-mailbox-register:
      SESSION_SECRET: 'SESSION_SECRET'
    elasticache-redis:
      REDIS_HOST: 'primary_endpoint_address'
      REDIS_AUTH_TOKEN: 'auth_token'
    application-insights:
      APPLICATIONINSIGHTS_CONNECTION_STRING: "APPLICATIONINSIGHTS_CONNECTION_STRING"
    # This secret will need to be created in your namespace (note it isn't in hmpps-templates-dev)
    # IRSA configuration in your namespace will also be required, and then uncomment serviceAccountName above.
    # sqs-hmpps-audit-secret:
    #   AUDIT_SQS_QUEUE_URL: 'sqs_queue_url'

generic-prometheus-alerts:
  targetApplication: hmpps-mailbox-register
  alertSeverity: moic
